---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# llbox

<!-- badges: start -->
<!-- badges: end -->

The goal of llbox is to ...

```{r longlat}
library(llbox)
to_sf <- function(x) {
  sf::st_sfc(sf::st_polygon(list(polygonate(x))), crs = "OGC:CRS84")
}
proj <- "+proj=murd3 +lat_1=30 +lat_2=50"
proj <- "+proj=tobmerc"
proj <- "+proj=laea"
proj <- "+proj=peirce_q"
cnt <- 0
gridx <- seq(-180, 180, by = 10)
gridy <- seq(0, 90, by = 15)
x0 <- list()
revm <- function(x) {
  x[seq(nrow(x), 1), ]
}
nv <- 180
for (i in seq_along(head(gridx, -1))) {
  for (j in seq_along(head(gridy, -1))) {
    ww <- west(x = gridx[i], y = gridy[j + c(0, 1)], nverts = nv)
    nn <- north(x = gridx[i + c(0, 1)], y = gridy[j + 1], nverts = nv)
    ee <- revm(east(x = gridx[i + 1], y = gridy[j + c(0, 1)], nverts = nv))
    ss <- revm(south(x = gridx[i + c(0, 1)], y = gridy[j], nverts = nv))
    x0  <- c(x0, list(rbind(ww, nn, ee, ss)))

  }
}


plot(sf::st_transform(do.call(c, lapply(x0, to_sf)), proj))


```
